---
title: "TIGIT DGE Analysis"
author: "BM"
date: "8/2/2021"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width=10, fig.height=10)
library(tidyverse)
library(limma)
library(NACHO)

##load data created with parse_join_RData_EGAD00010001515.R
load("../../EGAD00010001515/EGAD00010001515.RData")

##use NACHO package to load RCC data
data_dir <- "../../EGAD00010001515"
ssheet_df <- data.frame(dirs = grep("md5",
                                    grep("EGAF", dir(pattern = "*RCC", path = data_dir, recursive = TRUE), value = TRUE),
                                    value = TRUE,
                                    invert = TRUE))
EGAD00010001515_RCC <- NACHO::load_rcc(data_directory = data_dir,
                                       ssheet_csv = ssheet_df,
                                       id_colname = "dirs",
                                       normalisation_method = "GLM")

expr_counts <- EGAD00010001515_RCC[["nacho"]] %>%
  filter(grepl("Endogenous", CodeClass)) %>%
  select(dirs, Name, Count_Norm) %>%
  pivot_wider(names_from = "Name", values_from = "Count_Norm") %>%
  column_to_rownames("dirs") %>%
  t()

EGAD00010001515_raw_count_end_tb <- EGAD00010001515_raw_count_tb %>% dplyr::filter(CodeClass %in% "Endogenous")

##parse tibble of raw_counts into DGE-friendly format
raw_count_dge <- EGAD00010001515_raw_count_end_tb %>% dplyr::select(Accession_nv, tidyselect::starts_with("NS")) %>%
                 dplyr::filter(Accession_nv %in% grep("ERCC", EGAD00010001515_raw_count_tb$Accession_nv, invert = TRUE, value = TRUE)) %>%
                                 tibble::column_to_rownames("Accession_nv") %>%
                                 as.matrix()
raw_count_tb <- EGAD00010001515_raw_count_end_tb

##because there are multiple regional samples per {patient_id} and per {ns_sample_id}, the colnames in metadata are different to dge
##so we need to take all root names from {ns_sample_id}, and generate the {ns_sample_region_id} column in metadata
dge_sample_list <- lapply(sort(colnames(raw_count_dge)), function(f){
  paste(stringi::stri_split(f, regex = "_")[[1]][1:3], collapse = "_")
})
names(dge_sample_list) <- sort(colnames(raw_count_dge))
dge_ns_tb <- tibble::as_tibble(t(as.data.frame(dge_sample_list)), rownames = "full")
colnames(dge_ns_tb) <- c("ns_sample_region_id", "ns_sample_id")
```

```{r TIGIT, include=FALSE}
##find ensembl_gene_id for known gene names and parse from expr_tb
TIGIT <- unlist(EGAD00010001515_raw_count_end_tb[EGAD00010001515_raw_count_end_tb$Name %in% "TIGIT",c(4)])
names(TIGIT) <- c("TIGIT")
expr_df <- EGAD00010001515_log2tpm_tb %>% dplyr::select(-external_gene_name) %>%
  dplyr::filter(refseq_mrna %in% TIGIT) %>%
  t() %>%
  tibble::as_tibble(., rownames = "ns_sample_region_id")
colnames(expr_df) <- expr_df[1,]
expr_df <- expr_df[-1,]
colnames(expr_df)[1] <- "ns_sample_region_id"
expr_df[,2:dim(expr_df)[2]] <- lapply(expr_df[,2:dim(expr_df)[2]], as.numeric)

  #######################
 ## median expression ##
#######################
  
##function
med_func <- function(df){
  tibble::as_tibble(as.data.frame(lapply(seq_along(df), function(x){
    vec <- df[[x]]
    if(is.numeric(vec[1])){
      medv <- median(vec)
      ifelv <- ifelse(vec > medv, "High", "Low")
      tbo <- tibble::tibble(ifelv, vec)
      colnames(tbo) <- paste(names(df)[x], c("group", "log2tpm"), sep="_")
      return(tbo)
    } else {
      tbo <- tibble::tibble(vec)
      colnames(tbo) <- names(df)[x]
      return(tbo)
    }
  })))
}

qua_func <- function(df){
  tibble::as_tibble(as.data.frame(lapply(seq_along(df), function(x){
    vec <- df[[x]]
    ovec <- c()
    if(is.numeric(vec[1])){
      quav <- quantile(vec)
      
      #quav_cut <- cut(vec, breaks = quav, labels = seq(1, length(quav) - 1))
      lvec <- unlist(lapply(vec, function(xx){
        if(xx < quav[2]){return("Low")}
        if(xx > quav[4]){return("High")}
        else{return("Int")}
      }))

      tbo <- tibble::tibble(lvec, vec)
      colnames(tbo) <- paste(names(df)[x], c("group", "log2tpm"), sep="_")
      return(tbo)
    } else {
      tbo <- tibble::tibble(vec)
      colnames(tbo) <- names(df)[x]
      return(tbo)
    }
  })))
}

ter_func <- function(df){
  tibble::as_tibble(as.data.frame(lapply(seq_along(df), function(x){
    vec <- df[[x]]
    ovec <- c()
    if(is.numeric(vec[1])){
      quav <- quantile(vec, c(0:3/3))
      
      #quav_cut <- cut(vec, breaks = quav, labels = seq(1, length(quav) - 1))
      lvec <- unlist(lapply(vec, function(xx){
        if(xx < quav[2]){return("Low")}
        if(xx > quav[3]){return("High")}
        else{return("Int")}
      }))

      tbo <- tibble::tibble(lvec, vec)
      colnames(tbo) <- paste(names(df)[x], c("group", "log2tpm"), sep="_")
      return(tbo)
    } else {
      tbo <- tibble::tibble(vec)
      colnames(tbo) <- names(df)[x]
      return(tbo)
    }
  })))
}

##rename colnames(expr_df)
if(!is.null(names(TIGIT))){
  colnames(expr_df)[colnames(expr_df) %in% TIGIT] <- paste(TIGIT, names(TIGIT), sep = "_")
}

median_tb <- med_func(expr_df)
quantile_tb <- qua_func(expr_df)
tertile_tb <- ter_func(expr_df)

metadata_ns <- dplyr::inner_join(dge_ns_tb, EGAD00010001515_metadata) %>%
               dplyr::inner_join(., median_tb)
metadata_ov <- EGAD00010001515_metadata %>% dplyr::filter(tissue %in% "Ovary")
metadata_ns_ov <- left_join(metadata_ov, metadata_ns)
ov_cols <- c("CodeClass", "Name", "Accession", "Accession_nv", metadata_ns_ov$ns_sample_region_id)
EGAD00010001515_raw_count_end_ov_tb <- EGAD00010001515_raw_count_end_tb[, colnames(EGAD00010001515_raw_count_end_tb) %in% ov_cols]

##NB that most patient data has same TIGTI grouping
raw_count_dge <- raw_count_dge[, colnames(raw_count_dge) %in% metadata_ns$ns_sample_region_id] 
raw_count_ov_dge <- raw_count_dge[, colnames(raw_count_dge) %in% ov_cols]
```
## TIGIT Analysis

Data was obtained from the [EGAS00001002839](https://ega-archive.org/studies/EGAS00001002839) study and parsed [here](https://github.com/brucemoran/kglennon_tigit/blob/master/R/parse_join_RData_EGAD00010001515.R)

Here a DGE analysis is conducted using Limma which can account for variation based on multiple samples 
derived from the same individual/tumour.

### TIGIT Groupings by median log2tpm expression
```{r table}
mtd <- metadata_ns_ov %>% dplyr::select(patient_id, NM_173799_TIGIT_group) %>% as.data.frame() %>% table()
knitr::kable(mtd)
```

### DGE Analysis based on TIGIT median grouping
```{r limma}
dge <- edgeR::DGEList(counts = raw_count_ov_dge)
norm_fac <- EGAD00010001515_raw_count_tb %>% 
            dplyr::filter(!CodeClass %in% c("Endogenous", "Negative")) %>% 
            dplyr::select(!!colnames(raw_count_ov_dge)) %>%
            dplyr::summarise(across(where(is.numeric), sum)) %>% 
            dplyr::mutate(across(where(is.numeric), ~ 1 /.x))
dge$samples$norm.factors <- unlist(norm_fac)

##model includes site, sample_type (FFPE, FF) and patient_id
design <- model.matrix(~ 0 + NM_173799_TIGIT_group + sample_type, metadata_ns_ov)
colnames(design) <- make.names(colnames(design))
#keep <- edgeR::filterByExpr(dge, design)
#dge <- dge[keep, keep.lib.sizes=FALSE]
#dge <- edgeR::calcNormFactors(dge)

##MDS plots
col_patient_id <- metadata_ns_ov$patient_id
levels(col_patient_id) <-  sample(rainbow(nlevels(col_patient_id)))
col_patient_id <- as.character(col_patient_id)
lcpm <- edgeR::cpm(dge, log = TRUE, prior.count = 0.5, group = "NM_173799_TIGIT_group")
med_high <- unlist(lapply(strsplit(as.vector(metadata_ns_ov$NM_173799_TIGIT_group),""),function(f){f[1]}))
condNames <- paste0(metadata_ns_ov$ns_sample_region_id, "_", med_high)
plotMDS(lcpm, labels = condNames, col = col_patient_id, cex = 1)
title(main="NM_173799_TIGIT_group, sample-region ID")
condNames <- med_high
plotMDS(lcpm, labels = condNames, col = col_patient_id, cex = 2)
title(main="NM_173799_TIGIT_group, High-Low only")

##voom
dcv <- voom(dge, design, plot=FALSE)

##DC: https://support.bioconductor.org/p/94280/#94290; https://support.bioconductor.org/p/59700/
dccor <- limma::duplicateCorrelation(dcv, block = metadata_ns_ov$patient_id)
dccor$consensus.correlation
dcdcv <- limma::voom(dge, design, correlation=dccor$consensus.correlation, block = metadata_ns_ov$patient_id)

##second time around: https://support.bioconductor.org/p/115484/
dccor <- limma::duplicateCorrelation(dcdcv, block=metadata_ns_ov$patient_id)
dccor$consensus.correlation
dcdcv <- limma::voom(dge, design, correlation=dccor$consensus.correlation, block = metadata_ns_ov$patient_id)

dcfit <- limma::lmFit(dcdcv, design, cor=dccor$consensus.correlation, block = metadata_ns_ov$patient_id)
dcmc <- makeContrasts(
          LowHigh = NM_173799_TIGIT_groupLow - NM_173799_TIGIT_groupHigh,
          levels=colnames(design))
dcfitmc <- contrasts.fit(dcfit, dcmc)
dcfitmc <- eBayes(dcfitmc, robust=TRUE)
summary(decideTests(dcfitmc))
TIGIT_High_vs_Low_tb <- tibble::as_tibble(topTreat(dcfitmc, coef=1, n=Inf), rownames="Accession_nv") %>%
                        dplyr::left_join(raw_count_tb[,c(2,4)], .) %>%
                        dplyr::arrange(adj.P.Val, decreasing = FALSE) %>%
                        dplyr::mutate(absFC = 2^logFC) %>%
                        dplyr::mutate(fgseaRank = seq(1:length(t))) 
```

### Sanity check logFC direction
``` {r sanity, echo = FALSE }
plotExps <- function(log2tpms, genes, mapgenes, conds, condcol, factors, tag){

    log2tpms_genes <- log2tpms[match(genes,rownames(log2tpms)),]
    if(dim(log2tpms_genes)[1]==0){
        print("No input found, check genes are in rownames of log2tpm input")
    }
    else{
        Factor <- rep(factors[1],dim(conds)[1])
        Factor[c(conds[condcol] == factors[2])]<-factors[2]
        
        mltgg <- data.frame(0,0,0)
        mltgg <- mltgg[-1,]
        if(!is.null(mapgenes)){
          genenames <- mapgenes %>% dplyr::filter(ensembl_gene_id %in% unlist(genes)) %>% dplyr::select(human_external_gene_name)
          genenames <- unlist(genenames)
        } else {
          genenames <- genes
        }
        for(xx in 1:length(genes)){
          mltgg <- rbind(mltgg, cbind(rep(genenames[xx], length(Factor)),
                                      reshape2::melt(log2tpms_genes[rownames(log2tpms_genes) %in% unlist(genes)[xx],]),
                                      Factor))
        }
        
        colnames(mltgg) <- c("Gene","sample","value","Factor")
        mltgg$Factor <- factor(mltgg$Factor,
                               levels = factors, 
                               ordered = TRUE)
        ggp <- ggplot(data = mltgg, aes(x = Gene, y = value)) +
               geom_boxplot(aes(colour = Factor)) +
               geom_jitter(aes(colour = Factor), position=position_dodge(0.8)) +
               labs(y = "log2TPM", title = paste0(tag, ": Expression per Group per Gene")) +
               scale_colour_manual(values = c("blue", "red")) +
               theme(axis.text.x = element_text(angle = 45, hjust = 1))
    }
    return(ggp)
}
log2tpms <- EGAD00010001515_log2tpm_tb[EGAD00010001515_log2tpm_tb$external_gene_name %in% head(TIGIT_High_vs_Low_tb$Name) ,colnames(EGAD00010001515_log2tpm_tb) %in% c("external_gene_name", metadata_ns_ov$ns_sample_region_id)] %>%
    as.data.frame() %>% column_to_rownames("external_gene_name")

suppressMessages(plotExps(log2tpms = log2tpms, genes = unlist(head(TIGIT_High_vs_Low_tb$Name)), mapgenes = NULL, conds = metadata_ns_ov, condcol = "NM_173799_TIGIT_group", factors = c("High", "Low"), tag = "Median TIGGIT High - Low log2TPM - EGAD00010001515"))
```

```{r outtab, results = 'asis'}
knitr::kable(TIGIT_High_vs_Low_tb)
```